name = "Pandoc"
uuid = "f853b5e0-b243-11e9-0043-7da5023c5ee7"
authors = ["Dheepak Krishnamurthy <me@kdheepak.com>"]
version = "0.1.1"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1"
